# Example config
Package = "shapes"
AssetPath = "../../sprites/player"
OutFile = "chica-shapes.go"
Files = [
    "Chica-SpearDown.aseprite",
    "Chica-WalkDown.aseprite",
    "Chica-Idle-Down.aseprite"
]